CREATE DATABASE GroSys
GO
USE GroSys
GO

CREATE TABLE NhanVien (
	MaNV NVARCHAR(50) PRIMARY KEY NOT NULL,
	MatKhau NVARCHAR(50) NOT NULL,
	Ten NVARCHAR(50) NOT NULL,
	SoDienThoai NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	Anh NVARCHAR(50) NULL,
	VaiTro BIT NOT NULL,
)

GO 

CREATE TABLE LoaiSanPham (
	MaLSP NVARCHAR(50) PRIMARY KEY NOT NULL,
	TenLSP NVARCHAR(50) NOT NULL,
	GhiChu NVARCHAR(250) NULL
)

GO
CREATE TABLE NhaSanXuat (
	MaNSX NVARCHAR(50) PRIMARY KEY NOT NULL,
	TenNSX NVARCHAR(50) NOT NULL,
	DiaChi NVARCHAR(50) NOT NULL,
)

GO
CREATE TABLE SanPham (
	MaSP NVARCHAR(50) PRIMARY KEY NOT NULL,
	TenSP NVARCHAR(50) NOT NULL,
	MaLSP NVARCHAR(50) NOT NULL,
	GiaNhap FLOAT NOT NULL,
	GiaBan FLOAT NOT NULL,
	NgayNhap DATE NOT NULL,
	NgaySanXuat DATE NOT NULL,
	HanSuDung DATE NOT NULL,
	DonViTinh NVARCHAR(20) NOT NULL,
	SoLuong INT NOT NULL,
	maNSX NVARCHAR(50) NOT NULL,
	Anh NVARCHAR(50) NULL,
	KhuyenMai INT DEFAULT 0,  
	FOREIGN KEY(MaLSP) REFERENCES LoaiSanPham(MaLSP) ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY(MaNSX) REFERENCES NhaSanXuat(MaNSX) ON DELETE NO ACTION ON UPDATE CASCADE
)


GO
CREATE TABLE HoaDon (
	MaHD nvarchar(50) PRIMARY KEY not null,
	NgayLHD NVARCHAR(50) NOT NULL,
	SoTien FLOAT NOT NULL,
	MaNV NVARCHAR(50),
	FOREIGN KEY(MaNV) REFERENCES NhanVien(MaNV) ON DELETE NO ACTION ON UPDATE CASCADE
)

GO
CREATE TABLE HoaDonChiTiet(
	MaHDCT INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	MaHD nvarchar(50) not null,
	MaSanPham nvarchar(50) not null,
	FOREIGN KEY(MaHD) REFERENCES HoaDon(MaHD) ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY(MaSanPham) REFERENCES SanPham(MaSP) ON DELETE NO ACTION ON UPDATE CASCADE
)

GO
CREATE TABLE HoiVien (
	MaHV NVARCHAR(50) PRIMARY KEY NOT NULL,
	TenHV NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	SDT NVARCHAR(50) NOT NULL,
)
GO
CREATE TABLE PhieuGiamGia (
	MaHV NVARCHAR(50) NOT NULL,
	MaSP NVARCHAR(50) NOT NULL,
	HanSD DATE NOT NULL,
	PRIMARY KEY (MaHV, MaSP),
	FOREIGN KEY(MaHV) REFERENCES HoiVien(MaHV),
	FOREIGN KEY(MaSP) REFERENCES SanPham(MaSP)
)



GO
CREATE TABLE NhaPhanPhoi (
	MaNPP NVARCHAR(50) NOT NULL PRIMARY KEY,
	TenNPP NVARCHAR(50) NOT NULL,
	DiaChi NVARCHAR(50) NOT NULL,
	NamHopTac DATE
)
GO
CREATE TABLE ChiTietHopDong (
	MaNPP NVARCHAR(50) NOT NULL,
	MaSP NVARCHAr(50) NOT NULL,
	SoLuong INT NOT NULL,
	PRIMARY KEY (MaSP,MaNPP),
	FOREIGN KEY(MaSP) REFERENCES SanPham(MaSP),
	FOREIGN KEY(MaNPP) REFERENCES NhaPhanPhoi(MaNPP)
	
)

	