/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grosys.UI;

/**
 *
 * @author Sang
 */
public class HoaDon extends javax.swing.JPanel {

    /**
     * Creates new form HoaDOn
     */
    public HoaDon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlCbbNhaSanXuat1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        pnlCbbNhaSanXuat2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnThemNPP = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnXuatFileExcel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnThongKe = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 720, 400));

        pnlCbbNhaSanXuat1.setBackground(new java.awt.Color(255, 255, 255));
        pnlCbbNhaSanXuat1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        pnlCbbNhaSanXuat1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCbbNhaSanXuat1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 240, -1));

        add(pnlCbbNhaSanXuat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 270, 70));

        pnlCbbNhaSanXuat2.setBackground(new java.awt.Color(255, 255, 255));
        pnlCbbNhaSanXuat2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        pnlCbbNhaSanXuat2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        pnlCbbNhaSanXuat2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 37, 230, 20));

        jLabel3.setText("Theo ngày, Nhân viên,...");
        pnlCbbNhaSanXuat2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 15, -1, -1));

        add(pnlCbbNhaSanXuat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 270, 70));

        btnThemNPP.setBackground(new java.awt.Color(73, 164, 255));
        btnThemNPP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Xuất Hóa Đơn");

        javax.swing.GroupLayout btnThemNPPLayout = new javax.swing.GroupLayout(btnThemNPP);
        btnThemNPP.setLayout(btnThemNPPLayout);
        btnThemNPPLayout.setHorizontalGroup(
            btnThemNPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnThemNPPLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        btnThemNPPLayout.setVerticalGroup(
            btnThemNPPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(btnThemNPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, 110, 30));

        btnXuatFileExcel.setBackground(new java.awt.Color(73, 164, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_send_file_20px_1.png"))); // NOI18N
        jLabel1.setText("Xuất File Excel");

        javax.swing.GroupLayout btnXuatFileExcelLayout = new javax.swing.GroupLayout(btnXuatFileExcel);
        btnXuatFileExcel.setLayout(btnXuatFileExcelLayout);
        btnXuatFileExcelLayout.setHorizontalGroup(
            btnXuatFileExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnXuatFileExcelLayout.setVerticalGroup(
            btnXuatFileExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(btnXuatFileExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 130, 30));

        btnThongKe.setBackground(new java.awt.Color(73, 164, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_chart_20px.png"))); // NOI18N
        jLabel2.setText("Thống kê");

        javax.swing.GroupLayout btnThongKeLayout = new javax.swing.GroupLayout(btnThongKe);
        btnThongKe.setLayout(btnThongKeLayout);
        btnThongKeLayout.setHorizontalGroup(
            btnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnThongKeLayout.setVerticalGroup(
            btnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 100, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnThemNPP;
    private javax.swing.JPanel btnThongKe;
    private javax.swing.JPanel btnXuatFileExcel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel pnlCbbNhaSanXuat1;
    private javax.swing.JPanel pnlCbbNhaSanXuat2;
    // End of variables declaration//GEN-END:variables
}
