/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grosys.UI;

import com.grosys.DAO1.SanPhamDAO;
import com.grosys.untity.SanPham;
import com.toedter.calendar.JCalendar;
import java.awt.Color;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.geom.RoundRectangle2D;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import utils.Auth;
import utils.RoundedPanel;
/**
 *
 * @author Sang
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    
    public MainFrame() {

        setUndecorated(true);
        initComponents();
        prepareUI();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlHeader = new RoundedPanel(20);
        lblTaiKhoan = new javax.swing.JLabel();
        lblTinNhan = new javax.swing.JLabel();
        lblThongBao = new javax.swing.JLabel();
        lbTrangchu = new javax.swing.JLabel();
        lblHuongDan = new javax.swing.JLabel();
        lblGioiThieu = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnlDashBoard = new RoundedPanel(30);
        pnlStaffImage = new RoundedPanel(150);
        lblImage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTenNhanVien = new javax.swing.JLabel();
        pnlKhuyenMai = new RoundedPanel(17);
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnlHoaDon = new RoundedPanel(17);
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnlNhanVien = new RoundedPanel(17);
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnlSanPham = new RoundedPanel(17);
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnlGiaoDich = new RoundedPanel(17);
        jLabel4 = new javax.swing.JLabel();
        pnlThongKe = new RoundedPanel(17);
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pnlHopTac = new RoundedPanel(17);
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        pnlMain = new RoundedPanel(30);
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new RoundedPanel(40);
        jLabel21 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 720));
        setSize(new java.awt.Dimension(1000, 720));

        jPanel1.setBackground(new java.awt.Color(239, 244, 247));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(10, 102, 194));
        pnlHeader.setToolTipText("");

        lblTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        lblTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_user_25px.png"))); // NOI18N
        lblTaiKhoan.setText("Tài khoản");
        lblTaiKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTaiKhoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTaiKhoanMouseExited(evt);
            }
        });

        lblTinNhan.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblTinNhan.setForeground(new java.awt.Color(255, 255, 255));
        lblTinNhan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTinNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_facebook_messenger_25px.png"))); // NOI18N
        lblTinNhan.setText("Tin nhắn");
        lblTinNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTinNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTinNhanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTinNhanMouseExited(evt);
            }
        });

        lblThongBao.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblThongBao.setForeground(new java.awt.Color(255, 255, 255));
        lblThongBao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongBao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_google_alerts_25px.png"))); // NOI18N
        lblThongBao.setText("Thông báo");
        lblThongBao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblThongBao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblThongBaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThongBaoMouseExited(evt);
            }
        });

        lbTrangchu.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lbTrangchu.setForeground(new java.awt.Color(255, 255, 255));
        lbTrangchu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTrangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_home_25px.png"))); // NOI18N
        lbTrangchu.setText("Trang chủ");
        lbTrangchu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbTrangchu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lbTrangchuFocusGained(evt);
            }
        });
        lbTrangchu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbTrangchuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbTrangchuMouseExited(evt);
            }
        });

        lblHuongDan.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblHuongDan.setForeground(new java.awt.Color(255, 255, 255));
        lblHuongDan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_help_30px.png"))); // NOI18N
        lblHuongDan.setText("Hướng dẫn");
        lblHuongDan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHuongDan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHuongDanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHuongDanMouseExited(evt);
            }
        });

        lblGioiThieu.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblGioiThieu.setForeground(new java.awt.Color(255, 255, 255));
        lblGioiThieu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_high_importance_24px.png"))); // NOI18N
        lblGioiThieu.setText("Giới thiệu");
        lblGioiThieu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGioiThieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGioiThieuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGioiThieuMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Gro");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Sys");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTrangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTaiKhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTinNhan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(lblHuongDan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGioiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaiKhoan)
                    .addComponent(lblTinNhan)
                    .addComponent(lblThongBao)
                    .addComponent(lbTrangchu)
                    .addComponent(lblHuongDan)
                    .addComponent(lblGioiThieu)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        jPanel1.add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 960, 70));

        pnlDashBoard.setBackground(new java.awt.Color(255, 255, 255));
        pnlDashBoard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlStaffImage.setOpaque(false);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_contacts_150px_1.png"))); // NOI18N

        javax.swing.GroupLayout pnlStaffImageLayout = new javax.swing.GroupLayout(pnlStaffImage);
        pnlStaffImage.setLayout(pnlStaffImageLayout);
        pnlStaffImageLayout.setHorizontalGroup(
            pnlStaffImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStaffImageLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlStaffImageLayout.setVerticalGroup(
            pnlStaffImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStaffImageLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlDashBoard.add(pnlStaffImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 22, 150, 150));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nhân viên");
        pnlDashBoard.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 110, -1));

        lblTenNhanVien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTenNhanVien.setForeground(new java.awt.Color(153, 153, 153));
        lblTenNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenNhanVien.setText("Nguyễn Văn A");
        pnlDashBoard.add(lblTenNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 150, -1));

        pnlKhuyenMai.setBackground(new java.awt.Color(250, 132, 71));
        pnlKhuyenMai.setForeground(new java.awt.Color(250, 197, 118));
        pnlKhuyenMai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlKhuyenMaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlKhuyenMaiMouseExited(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Khuyến mãi");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_combo_chart_30px.png"))); // NOI18N

        javax.swing.GroupLayout pnlKhuyenMaiLayout = new javax.swing.GroupLayout(pnlKhuyenMai);
        pnlKhuyenMai.setLayout(pnlKhuyenMaiLayout);
        pnlKhuyenMaiLayout.setHorizontalGroup(
            pnlKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlKhuyenMaiLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pnlKhuyenMaiLayout.setVerticalGroup(
            pnlKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKhuyenMaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        pnlDashBoard.add(pnlKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 90, 60));

        pnlHoaDon.setBackground(new java.awt.Color(127, 193, 94));
        pnlHoaDon.setForeground(new java.awt.Color(156, 199, 135));
        pnlHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlHoaDonMouseExited(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Hóa Đơn");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_receipt_and_change_30px.png"))); // NOI18N

        javax.swing.GroupLayout pnlHoaDonLayout = new javax.swing.GroupLayout(pnlHoaDon);
        pnlHoaDon.setLayout(pnlHoaDonLayout);
        pnlHoaDonLayout.setHorizontalGroup(
            pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHoaDonLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
            .addGroup(pnlHoaDonLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHoaDonLayout.setVerticalGroup(
            pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        pnlDashBoard.add(pnlHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 90, -1));

        pnlNhanVien.setBackground(new java.awt.Color(254, 135, 138));
        pnlNhanVien.setForeground(new java.awt.Color(252, 161, 163));
        pnlNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlNhanVienMouseExited(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nhân Viên");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_staff_30px.png"))); // NOI18N

        javax.swing.GroupLayout pnlNhanVienLayout = new javax.swing.GroupLayout(pnlNhanVien);
        pnlNhanVien.setLayout(pnlNhanVienLayout);
        pnlNhanVienLayout.setHorizontalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlNhanVienLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel13)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pnlNhanVienLayout.setVerticalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        pnlDashBoard.add(pnlNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 90, 60));

        pnlSanPham.setBackground(new java.awt.Color(112, 181, 249));
        pnlSanPham.setForeground(new java.awt.Color(150, 203, 255));
        pnlSanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSanPhamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSanPhamMouseExited(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kho");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_warehouse_30px.png"))); // NOI18N

        javax.swing.GroupLayout pnlSanPhamLayout = new javax.swing.GroupLayout(pnlSanPham);
        pnlSanPham.setLayout(pnlSanPhamLayout);
        pnlSanPhamLayout.setHorizontalGroup(
            pnlSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        pnlSanPhamLayout.setVerticalGroup(
            pnlSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pnlDashBoard.add(pnlSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 90, 60));

        pnlGiaoDich.setBackground(new java.awt.Color(242, 242, 242));
        pnlGiaoDich.setForeground(new java.awt.Color(242, 242, 242));
        pnlGiaoDich.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlGiaoDich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlGiaoDichMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlGiaoDichMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Giao dịch");

        javax.swing.GroupLayout pnlGiaoDichLayout = new javax.swing.GroupLayout(pnlGiaoDich);
        pnlGiaoDich.setLayout(pnlGiaoDichLayout);
        pnlGiaoDichLayout.setHorizontalGroup(
            pnlGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(pnlGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlGiaoDichLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlGiaoDichLayout.setVerticalGroup(
            pnlGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(pnlGiaoDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlGiaoDichLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnlDashBoard.add(pnlGiaoDich, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, 50));

        pnlThongKe.setBackground(new java.awt.Color(250, 185, 88));
        pnlThongKe.setForeground(new java.awt.Color(250, 197, 118));
        pnlThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlThongKeMouseExited(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Thống Kê");

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_combo_chart_30px.png"))); // NOI18N

        javax.swing.GroupLayout pnlThongKeLayout = new javax.swing.GroupLayout(pnlThongKe);
        pnlThongKe.setLayout(pnlThongKeLayout);
        pnlThongKeLayout.setHorizontalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlThongKeLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel20)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pnlThongKeLayout.setVerticalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        pnlDashBoard.add(pnlThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 90, 60));

        pnlHopTac.setBackground(new java.awt.Color(230, 62, 201));
        pnlHopTac.setForeground(new java.awt.Color(250, 197, 118));
        pnlHopTac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlHopTac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlHopTacMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlHopTacMouseExited(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Hợp tác");

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_combo_chart_30px.png"))); // NOI18N

        javax.swing.GroupLayout pnlHopTacLayout = new javax.swing.GroupLayout(pnlHopTac);
        pnlHopTac.setLayout(pnlHopTacLayout);
        pnlHopTacLayout.setHorizontalGroup(
            pnlHopTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlHopTacLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel24)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pnlHopTacLayout.setVerticalGroup(
            pnlHopTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHopTacLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addContainerGap())
        );

        pnlDashBoard.add(pnlHopTac, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 90, 60));

        btnThoat.setBackground(new java.awt.Color(255, 255, 255));
        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThoat.setText("THOÁT");
        pnlDashBoard.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 200, -1));

        jPanel1.add(pnlDashBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 220, 580));

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setForeground(new java.awt.Color(197, 193, 193));
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_search_35px.png"))); // NOI18N
        pnlMain.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 70, 40));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("Cập nhật tin tức");
        pnlMain.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 250, 40));
        pnlMain.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 660, 10));

        jPanel2.setBackground(new java.awt.Color(211, 209, 209));
        jPanel2.setOpaque(false);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Tây Nguyên Town");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(15, Short.MAX_VALUE)
                    .addComponent(jLabel21)
                    .addContainerGap(9, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnlMain.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 190, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Welcome_1.gif"))); // NOI18N
        pnlMain.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 660, 360));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(250, 197, 118));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Chào Mừng trở lại");
        pnlMain.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 410, 40));

        lblClock.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblClock.setForeground(new java.awt.Color(153, 153, 153));
        lblClock.setText("Đồng hồ");
        pnlMain.add(lblClock, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 160, -1));
        pnlMain.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 130, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setText("Được tạo bởi : Nhóm 7");
        pnlMain.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 550, 160, -1));

        jPanel1.add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 720, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbTrangchuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lbTrangchuFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lbTrangchuFocusGained

    private void lbTrangchuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTrangchuMouseEntered
        // TODO add your handling code here:
        LabelfocusGain(lbTrangchu, "src\\main\\resources\\Icons\\icons8_home_25px_1.png");
    }//GEN-LAST:event_lbTrangchuMouseEntered

    private void lbTrangchuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbTrangchuMouseExited
        // TODO add your handling code here:
        labelfocusLost(lbTrangchu, "src\\main\\resources\\Icons\\icons8_home_25px.png");
    }//GEN-LAST:event_lbTrangchuMouseExited

    private void lblTaiKhoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTaiKhoanMouseEntered
        // TODO add your handling code here:
        LabelfocusGain(lblTaiKhoan, "src\\main\\resources\\Icons\\icons8_user_25px_1.png");
    }//GEN-LAST:event_lblTaiKhoanMouseEntered

    private void pnlGiaoDichMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGiaoDichMouseEntered
        // TODO add your handling code here:
        pnlGiaoDich.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_pnlGiaoDichMouseEntered

    private void pnlGiaoDichMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGiaoDichMouseExited
        // TODO add your handling code here:
        pnlGiaoDich.setBackground(new Color(242,242,242));
    }//GEN-LAST:event_pnlGiaoDichMouseExited

    private void lblTaiKhoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTaiKhoanMouseExited
        // TODO add your handling code here:
        labelfocusLost(lblTaiKhoan, "src\\main\\resources\\Icons\\icons8_user_25px.png");
    }//GEN-LAST:event_lblTaiKhoanMouseExited

    private void lblTinNhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTinNhanMouseEntered
        // TODO add your handling code here:
        LabelfocusGain(lblTinNhan, "src\\main\\resources\\Icons\\icons8_facebook_messenger_25px_2.png");
    }//GEN-LAST:event_lblTinNhanMouseEntered

    private void lblTinNhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTinNhanMouseExited
        // TODO add your handling code here:
        labelfocusLost(lblTinNhan, "src\\main\\resources\\Icons\\icons8_facebook_messenger_25px.png");
    }//GEN-LAST:event_lblTinNhanMouseExited

    private void lblThongBaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongBaoMouseEntered
        // TODO add your handling code here:
        LabelfocusGain(lblThongBao, "src\\main\\resources\\Icons\\icons8_google_alerts_25px_1.png");
    }//GEN-LAST:event_lblThongBaoMouseEntered

    private void lblThongBaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongBaoMouseExited
        // TODO add your handling code here:
        labelfocusLost(lblThongBao, "src\\main\\resources\\Icons\\icons8_google_alerts_25px.png");
    }//GEN-LAST:event_lblThongBaoMouseExited

    private void lblHuongDanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHuongDanMouseEntered
        // TODO add your handling code here:
        LabelfocusGain(lblHuongDan, "src\\main\\resources\\Icons\\icons8_help_30px_1.png");
    }//GEN-LAST:event_lblHuongDanMouseEntered

    private void lblHuongDanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHuongDanMouseExited
        // TODO add your handling code here:
        labelfocusLost(lblHuongDan, "src\\main\\resources\\Icons\\icons8_help_30px.png");
    }//GEN-LAST:event_lblHuongDanMouseExited

    private void lblGioiThieuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGioiThieuMouseEntered
        // TODO add your handling code here:
        LabelfocusGain(lblGioiThieu, "src\\main\\resources\\Icons\\icons8_high_importance_24px_1.png");
    }//GEN-LAST:event_lblGioiThieuMouseEntered

    private void lblGioiThieuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGioiThieuMouseExited
        // TODO add your handling code here:
        labelfocusLost(lblGioiThieu, "src\\main\\resources\\Icons\\icons8_high_importance_24px.png");
    }//GEN-LAST:event_lblGioiThieuMouseExited

    private void pnlSanPhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSanPhamMouseEntered
        // TODO add your handling code here:
        pnlSanPham.setBackground(new Color(150,203,255));
    }//GEN-LAST:event_pnlSanPhamMouseEntered

    private void pnlSanPhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSanPhamMouseExited
        // TODO add your handling code here:
        pnlSanPham.setBackground(new Color(112,181,249));
    }//GEN-LAST:event_pnlSanPhamMouseExited

    private void pnlHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHoaDonMouseEntered
        // TODO add your handling code here:
        pnlHoaDon.setBackground(new Color(156,199,135));
    }//GEN-LAST:event_pnlHoaDonMouseEntered

    private void pnlHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHoaDonMouseExited
        // TODO add your handling code here:
        pnlHoaDon.setBackground(new Color(127,193,94));
    }//GEN-LAST:event_pnlHoaDonMouseExited

    private void pnlKhuyenMaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhuyenMaiMouseEntered
        // TODO add your handling code here:
        pnlKhuyenMai.setBackground(new Color(250,197,118));
    }//GEN-LAST:event_pnlKhuyenMaiMouseEntered

    private void pnlKhuyenMaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlKhuyenMaiMouseExited
        // TODO add your handling code here:
        pnlKhuyenMai.setBackground(new Color(250,132,71));
    }//GEN-LAST:event_pnlKhuyenMaiMouseExited

    private void pnlNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhanVienMouseEntered
        // TODO add your handling code here:
        pnlNhanVien.setBackground(new Color(252,161,163));
    }//GEN-LAST:event_pnlNhanVienMouseEntered

    private void pnlNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNhanVienMouseExited
        // TODO add your handling code here:
        pnlNhanVien.setBackground(new Color(254,135,138));
    }//GEN-LAST:event_pnlNhanVienMouseExited

    private void pnlThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongKeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlThongKeMouseEntered

    private void pnlThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThongKeMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlThongKeMouseExited

    private void pnlHopTacMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHopTacMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlHopTacMouseEntered

    private void pnlHopTacMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHopTacMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlHopTacMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbTrangchu;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblGioiThieu;
    private javax.swing.JLabel lblHuongDan;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JLabel lblThongBao;
    private javax.swing.JLabel lblTinNhan;
    private javax.swing.JPanel pnlDashBoard;
    private javax.swing.JPanel pnlGiaoDich;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlHoaDon;
    private javax.swing.JPanel pnlHopTac;
    private javax.swing.JPanel pnlKhuyenMai;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlNhanVien;
    private javax.swing.JPanel pnlSanPham;
    private javax.swing.JPanel pnlStaffImage;
    private javax.swing.JPanel pnlThongKe;
    // End of variables declaration//GEN-END:variables

    private void prepareUI() {
        this.setSize(1000, 700);
        setLocationRelativeTo(null);
        addComponentListener(new ComponentAdapter() {
               @Override
                public void componentResized(ComponentEvent e) {
                    setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 25, 25));
                    
                }
            });
        pnlHeader.setOpaque(false);
        pnlDashBoard.setOpaque(false);
        pnlMain.setOpaque(false);
        pnlGiaoDich.setOpaque(false);
        pnlHoaDon.setOpaque(false);
        pnlSanPham.setOpaque(false);
        pnlNhanVien.setOpaque(false);
        pnlKhuyenMai.setOpaque(false);
        pnlThongKe.setOpaque(false);
        pnlHopTac.setOpaque(false);
        
        
        lblTenNhanVien.setText(Auth.user.getHoten());
    }

    private void LabelfocusGain(JLabel label, String path) {
        label.setForeground(new Color(255, 199, 69));
        label.setIcon(new ImageIcon(path));
    }

    private void labelfocusLost(JLabel label, String path) {
        label.setForeground(Color.WHITE);
        label.setIcon(new ImageIcon(path));
    }
    
    
    
}
