/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grosys.UI;

import utils.HeaderColor;

/**
 *
 * @author Sang
 */
public class NhanVien extends javax.swing.JPanel {

    /**
     * Creates new form NhanVien
     */
    public NhanVien() {
        initComponents();
        prepareUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        VaiTroGroup = new javax.swing.ButtonGroup();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        lblImage = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        rdoNhanVien = new javax.swing.JRadioButton();
        rdoQuanLy = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtXacNhan = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThongKe = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnXuatFileExcel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnThongKe1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnXuatFileExcel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jLabel16.setText("Mã Nhân Viên:");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblNhanVien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaNV", "TenNV", "Email", "SDT", "Vai Tro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVien.setRowHeight(25);
        tblNhanVien.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tblNhanVien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblNhanVien.setShowGrid(true);
        tblNhanVien.setShowVerticalLines(false);
        tblNhanVien.getTableHeader().setReorderingAllowed(false);
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(tblNhanVien);

        add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 375, 720, 160));

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 45, 191, 180));
        add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 48, 331, -1));

        jLabel14.setText("Mã Nhân Viên:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 52, 93, -1));

        jLabel15.setText("Tên Nhân Viên:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 104, 93, -1));
        add(txtTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 100, 331, -1));

        jLabel17.setText("Số Điện Thoại:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 155, 93, -1));
        add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 151, 331, -1));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 207, 331, -1));

        jLabel18.setText("Email:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 211, 93, -1));

        VaiTroGroup.add(rdoNhanVien);
        rdoNhanVien.setText("Nhân Viên");
        add(rdoNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 249, 95, -1));

        VaiTroGroup.add(rdoQuanLy);
        rdoQuanLy.setText("Quản Lý");
        add(rdoQuanLy, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 249, 99, -1));

        jLabel19.setText("Vai Trò:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 255, 93, -1));
        add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 295, 331, -1));

        jLabel20.setText("Mật Khẩu:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 299, 93, -1));

        jLabel21.setText("Xác Nhận:");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 337, 93, -1));
        add(txtXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 333, 331, -1));

        btnThem.setBackground(new java.awt.Color(73, 164, 255));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 90, 32));

        btnXoa.setBackground(new java.awt.Color(73, 164, 255));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 73, 32));

        btnMoi.setBackground(new java.awt.Color(73, 164, 255));
        btnMoi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnMoi.setText("Mới");
        add(btnMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 73, 27));

        btnSua.setBackground(new java.awt.Color(73, 164, 255));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 90, 27));

        btnThongKe.setBackground(new java.awt.Color(73, 164, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_chart_20px.png"))); // NOI18N
        jLabel2.setText("Thống kê");

        javax.swing.GroupLayout btnThongKeLayout = new javax.swing.GroupLayout(btnThongKe);
        btnThongKe.setLayout(btnThongKeLayout);
        btnThongKeLayout.setHorizontalGroup(
            btnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnThongKeLayout.setVerticalGroup(
            btnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 100, 30));

        btnXuatFileExcel.setBackground(new java.awt.Color(73, 164, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_send_file_20px_1.png"))); // NOI18N
        jLabel1.setText("Xuất File Excel");

        javax.swing.GroupLayout btnXuatFileExcelLayout = new javax.swing.GroupLayout(btnXuatFileExcel);
        btnXuatFileExcel.setLayout(btnXuatFileExcelLayout);
        btnXuatFileExcelLayout.setHorizontalGroup(
            btnXuatFileExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnXuatFileExcelLayout.setVerticalGroup(
            btnXuatFileExcelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(btnXuatFileExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 130, 30));

        btnThongKe1.setBackground(new java.awt.Color(73, 164, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_chart_20px.png"))); // NOI18N
        jLabel3.setText("Thống kê");

        javax.swing.GroupLayout btnThongKe1Layout = new javax.swing.GroupLayout(btnThongKe1);
        btnThongKe1.setLayout(btnThongKe1Layout);
        btnThongKe1Layout.setHorizontalGroup(
            btnThongKe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnThongKe1Layout.setVerticalGroup(
            btnThongKe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(btnThongKe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, 100, 30));

        btnXuatFileExcel1.setBackground(new java.awt.Color(73, 164, 255));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_send_file_20px_1.png"))); // NOI18N
        jLabel4.setText("Xuất File Excel");

        javax.swing.GroupLayout btnXuatFileExcel1Layout = new javax.swing.GroupLayout(btnXuatFileExcel1);
        btnXuatFileExcel1.setLayout(btnXuatFileExcel1Layout);
        btnXuatFileExcel1Layout.setHorizontalGroup(
            btnXuatFileExcel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnXuatFileExcel1Layout.setVerticalGroup(
            btnXuatFileExcel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(btnXuatFileExcel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 130, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblNhanVienMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup VaiTroGroup;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JPanel btnThongKe;
    private javax.swing.JPanel btnThongKe1;
    private javax.swing.JButton btnXoa;
    private javax.swing.JPanel btnXuatFileExcel;
    private javax.swing.JPanel btnXuatFileExcel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblImage;
    private javax.swing.JRadioButton rdoNhanVien;
    private javax.swing.JRadioButton rdoQuanLy;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtXacNhan;
    // End of variables declaration//GEN-END:variables

    private void prepareUI() {
        tblNhanVien.getTableHeader().setDefaultRenderer(new HeaderColor());
    }
}
